//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="marker" type="{http://www.trapster.com/schema/2.0.0/trapster}markerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="added" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="removed" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="displayname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailaddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwdusernamehash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mobilepwdhash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usercredlevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alertradius" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signupepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastvoteepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="totaluservotes" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="karma" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tosagreed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trustedgrouppref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="privmsgpref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="smsaddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="moderatorlevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loggedontositeflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="newsletterflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailconfflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userstatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastkarma" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sipallowedflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loginfailures" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="modapplyepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastapiepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastwebepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="confirmepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="confirmmethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="color" type="{http://www.trapster.com/schema/2.0.0/trapster}colorAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="image" type="{http://www.trapster.com/schema/2.0.0/trapster}imageAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="string" type="{http://www.trapster.com/schema/2.0.0/trapster}stringAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="trapcategory" type="{http://www.trapster.com/schema/2.0.0/trapster}trapCategoryAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="traptype" type="{http://www.trapster.com/schema/2.0.0/trapster}trapTypeAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addedtheme" type="{http://www.trapster.com/schema/2.0.0/trapster}themeAttributeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="removedtheme" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="addedpoi" type="{http://www.trapster.com/schema/2.0.0/trapster}poitopicsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="removedpoi" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patrolLines" type="{http://www.trapster.com/schema/2.0.0/trapster}patrolPointType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataType", propOrder = {
    "marker",
    "added",
    "removed",
    "id",
    "displayname",
    "emailaddr",
    "pwdusernamehash",
    "mobilepwdhash",
    "usercredlevel",
    "info",
    "alertradius",
    "alert",
    "signupepochtime",
    "lastvoteepochtime",
    "totaluservotes",
    "karma",
    "tosagreed",
    "trustedgrouppref",
    "privmsgpref",
    "smsaddr",
    "moderatorlevel",
    "loggedontositeflag",
    "newsletterflag",
    "emailconfflag",
    "userstatus",
    "lastkarma",
    "sipallowedflag",
    "loginfailures",
    "modapplyepochtime",
    "lastapiepochtime",
    "lastwebepochtime",
    "confirmepochtime",
    "confirmmethod",
    "color",
    "image",
    "string",
    "trapcategory",
    "traptype",
    "addedtheme",
    "removedtheme",
    "addedpoi",
    "removedpoi",
    "patrolLines"
})
public class DataType {

    protected List<MarkerType> marker;
    protected List<String> added;
    protected List<String> removed;
    protected Long id;
    protected String displayname;
    protected String emailaddr;
    protected String pwdusernamehash;
    protected String mobilepwdhash;
    protected Integer usercredlevel;
    protected String info;
    protected Double alertradius;
    protected String alert;
    protected Long signupepochtime;
    protected Long lastvoteepochtime;
    protected Integer totaluservotes;
    protected Integer karma;
    protected String tosagreed;
    protected String trustedgrouppref;
    protected String privmsgpref;
    protected String smsaddr;
    protected String moderatorlevel;
    protected String loggedontositeflag;
    protected String newsletterflag;
    protected String emailconfflag;
    protected String userstatus;
    protected Integer lastkarma;
    protected String sipallowedflag;
    protected Integer loginfailures;
    protected Long modapplyepochtime;
    protected Long lastapiepochtime;
    protected Long lastwebepochtime;
    protected Long confirmepochtime;
    protected String confirmmethod;
    protected List<ColorAttributeType> color;
    protected List<ImageAttributeType> image;
    protected List<StringAttributeType> string;
    protected List<TrapCategoryAttributeType> trapcategory;
    protected List<TrapTypeAttributeType> traptype;
    protected List<ThemeAttributeType> addedtheme;
    protected List<String> removedtheme;
    protected List<PoitopicsType> addedpoi;
    protected List<String> removedpoi;
    protected List<PatrolPointType> patrolLines;

    /**
     * Gets the value of the marker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarkerType }
     * 
     * 
     */
    public List<MarkerType> getMarker() {
        if (marker == null) {
            marker = new ArrayList<MarkerType>();
        }
        return this.marker;
    }

    /**
     * Gets the value of the added property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the added property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdded().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdded() {
        if (added == null) {
            added = new ArrayList<String>();
        }
        return this.added;
    }

    /**
     * Gets the value of the removed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemoved().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemoved() {
        if (removed == null) {
            removed = new ArrayList<String>();
        }
        return this.removed;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the displayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * Sets the value of the displayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayname(String value) {
        this.displayname = value;
    }

    /**
     * Gets the value of the emailaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailaddr() {
        return emailaddr;
    }

    /**
     * Sets the value of the emailaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailaddr(String value) {
        this.emailaddr = value;
    }

    /**
     * Gets the value of the pwdusernamehash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwdusernamehash() {
        return pwdusernamehash;
    }

    /**
     * Sets the value of the pwdusernamehash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwdusernamehash(String value) {
        this.pwdusernamehash = value;
    }

    /**
     * Gets the value of the mobilepwdhash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilepwdhash() {
        return mobilepwdhash;
    }

    /**
     * Sets the value of the mobilepwdhash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilepwdhash(String value) {
        this.mobilepwdhash = value;
    }

    /**
     * Gets the value of the usercredlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsercredlevel() {
        return usercredlevel;
    }

    /**
     * Sets the value of the usercredlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsercredlevel(Integer value) {
        this.usercredlevel = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the alertradius property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAlertradius() {
        return alertradius;
    }

    /**
     * Sets the value of the alertradius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlertradius(Double value) {
        this.alertradius = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlert() {
        return alert;
    }

    /**
     * Sets the value of the alert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlert(String value) {
        this.alert = value;
    }

    /**
     * Gets the value of the signupepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSignupepochtime() {
        return signupepochtime;
    }

    /**
     * Sets the value of the signupepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSignupepochtime(Long value) {
        this.signupepochtime = value;
    }

    /**
     * Gets the value of the lastvoteepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastvoteepochtime() {
        return lastvoteepochtime;
    }

    /**
     * Sets the value of the lastvoteepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastvoteepochtime(Long value) {
        this.lastvoteepochtime = value;
    }

    /**
     * Gets the value of the totaluservotes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotaluservotes() {
        return totaluservotes;
    }

    /**
     * Sets the value of the totaluservotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotaluservotes(Integer value) {
        this.totaluservotes = value;
    }

    /**
     * Gets the value of the karma property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKarma() {
        return karma;
    }

    /**
     * Sets the value of the karma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKarma(Integer value) {
        this.karma = value;
    }

    /**
     * Gets the value of the tosagreed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTosagreed() {
        return tosagreed;
    }

    /**
     * Sets the value of the tosagreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTosagreed(String value) {
        this.tosagreed = value;
    }

    /**
     * Gets the value of the trustedgrouppref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrustedgrouppref() {
        return trustedgrouppref;
    }

    /**
     * Sets the value of the trustedgrouppref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrustedgrouppref(String value) {
        this.trustedgrouppref = value;
    }

    /**
     * Gets the value of the privmsgpref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivmsgpref() {
        return privmsgpref;
    }

    /**
     * Sets the value of the privmsgpref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivmsgpref(String value) {
        this.privmsgpref = value;
    }

    /**
     * Gets the value of the smsaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmsaddr() {
        return smsaddr;
    }

    /**
     * Sets the value of the smsaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmsaddr(String value) {
        this.smsaddr = value;
    }

    /**
     * Gets the value of the moderatorlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeratorlevel() {
        return moderatorlevel;
    }

    /**
     * Sets the value of the moderatorlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeratorlevel(String value) {
        this.moderatorlevel = value;
    }

    /**
     * Gets the value of the loggedontositeflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggedontositeflag() {
        return loggedontositeflag;
    }

    /**
     * Sets the value of the loggedontositeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggedontositeflag(String value) {
        this.loggedontositeflag = value;
    }

    /**
     * Gets the value of the newsletterflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsletterflag() {
        return newsletterflag;
    }

    /**
     * Sets the value of the newsletterflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsletterflag(String value) {
        this.newsletterflag = value;
    }

    /**
     * Gets the value of the emailconfflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailconfflag() {
        return emailconfflag;
    }

    /**
     * Sets the value of the emailconfflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailconfflag(String value) {
        this.emailconfflag = value;
    }

    /**
     * Gets the value of the userstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstatus() {
        return userstatus;
    }

    /**
     * Sets the value of the userstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstatus(String value) {
        this.userstatus = value;
    }

    /**
     * Gets the value of the lastkarma property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastkarma() {
        return lastkarma;
    }

    /**
     * Sets the value of the lastkarma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastkarma(Integer value) {
        this.lastkarma = value;
    }

    /**
     * Gets the value of the sipallowedflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSipallowedflag() {
        return sipallowedflag;
    }

    /**
     * Sets the value of the sipallowedflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSipallowedflag(String value) {
        this.sipallowedflag = value;
    }

    /**
     * Gets the value of the loginfailures property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoginfailures() {
        return loginfailures;
    }

    /**
     * Sets the value of the loginfailures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoginfailures(Integer value) {
        this.loginfailures = value;
    }

    /**
     * Gets the value of the modapplyepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getModapplyepochtime() {
        return modapplyepochtime;
    }

    /**
     * Sets the value of the modapplyepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setModapplyepochtime(Long value) {
        this.modapplyepochtime = value;
    }

    /**
     * Gets the value of the lastapiepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastapiepochtime() {
        return lastapiepochtime;
    }

    /**
     * Sets the value of the lastapiepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastapiepochtime(Long value) {
        this.lastapiepochtime = value;
    }

    /**
     * Gets the value of the lastwebepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastwebepochtime() {
        return lastwebepochtime;
    }

    /**
     * Sets the value of the lastwebepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastwebepochtime(Long value) {
        this.lastwebepochtime = value;
    }

    /**
     * Gets the value of the confirmepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfirmepochtime() {
        return confirmepochtime;
    }

    /**
     * Sets the value of the confirmepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfirmepochtime(Long value) {
        this.confirmepochtime = value;
    }

    /**
     * Gets the value of the confirmmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmmethod() {
        return confirmmethod;
    }

    /**
     * Sets the value of the confirmmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmmethod(String value) {
        this.confirmmethod = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the color property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColorAttributeType }
     * 
     * 
     */
    public List<ColorAttributeType> getColor() {
        if (color == null) {
            color = new ArrayList<ColorAttributeType>();
        }
        return this.color;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageAttributeType }
     * 
     * 
     */
    public List<ImageAttributeType> getImage() {
        if (image == null) {
            image = new ArrayList<ImageAttributeType>();
        }
        return this.image;
    }

    /**
     * Gets the value of the string property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the string property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getString().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringAttributeType }
     * 
     * 
     */
    public List<StringAttributeType> getString() {
        if (string == null) {
            string = new ArrayList<StringAttributeType>();
        }
        return this.string;
    }

    /**
     * Gets the value of the trapcategory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trapcategory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrapcategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrapCategoryAttributeType }
     * 
     * 
     */
    public List<TrapCategoryAttributeType> getTrapcategory() {
        if (trapcategory == null) {
            trapcategory = new ArrayList<TrapCategoryAttributeType>();
        }
        return this.trapcategory;
    }

    /**
     * Gets the value of the traptype property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traptype property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraptype().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrapTypeAttributeType }
     * 
     * 
     */
    public List<TrapTypeAttributeType> getTraptype() {
        if (traptype == null) {
            traptype = new ArrayList<TrapTypeAttributeType>();
        }
        return this.traptype;
    }

    /**
     * Gets the value of the addedtheme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addedtheme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddedtheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ThemeAttributeType }
     * 
     * 
     */
    public List<ThemeAttributeType> getAddedtheme() {
        if (addedtheme == null) {
            addedtheme = new ArrayList<ThemeAttributeType>();
        }
        return this.addedtheme;
    }

    /**
     * Gets the value of the removedtheme property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removedtheme property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemovedtheme().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemovedtheme() {
        if (removedtheme == null) {
            removedtheme = new ArrayList<String>();
        }
        return this.removedtheme;
    }

    /**
     * Gets the value of the addedpoi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addedpoi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddedpoi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoitopicsType }
     * 
     * 
     */
    public List<PoitopicsType> getAddedpoi() {
        if (addedpoi == null) {
            addedpoi = new ArrayList<PoitopicsType>();
        }
        return this.addedpoi;
    }

    /**
     * Gets the value of the removedpoi property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removedpoi property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemovedpoi().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemovedpoi() {
        if (removedpoi == null) {
            removedpoi = new ArrayList<String>();
        }
        return this.removedpoi;
    }

    /**
     * Gets the value of the patrolLines property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patrolLines property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatrolLines().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatrolPointType }
     * 
     * 
     */
    public List<PatrolPointType> getPatrolLines() {
        if (patrolLines == null) {
            patrolLines = new ArrayList<PatrolPointType>();
        }
        return this.patrolLines;
    }

}
