//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for markerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="markerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="traptypeid" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="numvotes" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="origdisplayname" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="lastupdatedisplayname" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="lastvoteepochtime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="trapaddress" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="trapcredlevel" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="lifetime" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="badgekey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "markerType", propOrder = {
    "id",
    "latitude",
    "longitude",
    "traptypeid",
    "numvotes",
    "origdisplayname",
    "lastupdatedisplayname",
    "lastvoteepochtime",
    "trapaddress",
    "trapcredlevel",
    "lifetime",
    "badgekey"
})
public class MarkerType {

    protected long id;
    protected double latitude;
    protected double longitude;
    protected long traptypeid;
    protected int numvotes;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String origdisplayname;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String lastupdatedisplayname;
    protected long lastvoteepochtime;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String trapaddress;
    protected int trapcredlevel;
    protected long lifetime;
    @XmlElement(required = true)
    protected String badgekey;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     */
    public double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     */
    public void setLatitude(double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     */
    public double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     */
    public void setLongitude(double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the traptypeid property.
     * 
     */
    public long getTraptypeid() {
        return traptypeid;
    }

    /**
     * Sets the value of the traptypeid property.
     * 
     */
    public void setTraptypeid(long value) {
        this.traptypeid = value;
    }

    /**
     * Gets the value of the numvotes property.
     * 
     */
    public int getNumvotes() {
        return numvotes;
    }

    /**
     * Sets the value of the numvotes property.
     * 
     */
    public void setNumvotes(int value) {
        this.numvotes = value;
    }

    /**
     * Gets the value of the origdisplayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigdisplayname() {
        return origdisplayname;
    }

    /**
     * Sets the value of the origdisplayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigdisplayname(String value) {
        this.origdisplayname = value;
    }

    /**
     * Gets the value of the lastupdatedisplayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastupdatedisplayname() {
        return lastupdatedisplayname;
    }

    /**
     * Sets the value of the lastupdatedisplayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastupdatedisplayname(String value) {
        this.lastupdatedisplayname = value;
    }

    /**
     * Gets the value of the lastvoteepochtime property.
     * 
     */
    public long getLastvoteepochtime() {
        return lastvoteepochtime;
    }

    /**
     * Sets the value of the lastvoteepochtime property.
     * 
     */
    public void setLastvoteepochtime(long value) {
        this.lastvoteepochtime = value;
    }

    /**
     * Gets the value of the trapaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrapaddress() {
        return trapaddress;
    }

    /**
     * Sets the value of the trapaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrapaddress(String value) {
        this.trapaddress = value;
    }

    /**
     * Gets the value of the trapcredlevel property.
     * 
     */
    public int getTrapcredlevel() {
        return trapcredlevel;
    }

    /**
     * Sets the value of the trapcredlevel property.
     * 
     */
    public void setTrapcredlevel(int value) {
        this.trapcredlevel = value;
    }

    /**
     * Gets the value of the lifetime property.
     * 
     */
    public long getLifetime() {
        return lifetime;
    }

    /**
     * Sets the value of the lifetime property.
     * 
     */
    public void setLifetime(long value) {
        this.lifetime = value;
    }

    /**
     * Gets the value of the badgekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBadgekey() {
        return badgekey;
    }

    /**
     * Sets the value of the badgekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBadgekey(String value) {
        this.badgekey = value;
    }

}
