//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.navteq.lbsp.ctg.trapster.modules.commons.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Trapster_QNAME = new QName("http://www.trapster.com/schema/2.0.0/trapster", "trapster");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.navteq.lbsp.ctg.trapster.modules.commons.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrapsterType }
     * 
     */
    public TrapsterType createTrapsterType() {
        return new TrapsterType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link ThemeLinkType }
     * 
     */
    public ThemeLinkType createThemeLinkType() {
        return new ThemeLinkType();
    }

    /**
     * Create an instance of {@link TrapsterResponseType }
     * 
     */
    public TrapsterResponseType createTrapsterResponseType() {
        return new TrapsterResponseType();
    }

    /**
     * Create an instance of {@link ColorAttributeType }
     * 
     */
    public ColorAttributeType createColorAttributeType() {
        return new ColorAttributeType();
    }

    /**
     * Create an instance of {@link TrapCategoryAttributeType }
     * 
     */
    public TrapCategoryAttributeType createTrapCategoryAttributeType() {
        return new TrapCategoryAttributeType();
    }

    /**
     * Create an instance of {@link MarkerType }
     * 
     */
    public MarkerType createMarkerType() {
        return new MarkerType();
    }

    /**
     * Create an instance of {@link ParamsType }
     * 
     */
    public ParamsType createParamsType() {
        return new ParamsType();
    }

    /**
     * Create an instance of {@link TrapsterRequestType }
     * 
     */
    public TrapsterRequestType createTrapsterRequestType() {
        return new TrapsterRequestType();
    }

    /**
     * Create an instance of {@link TrapTypeLevelListType }
     * 
     */
    public TrapTypeLevelListType createTrapTypeLevelListType() {
        return new TrapTypeLevelListType();
    }

    /**
     * Create an instance of {@link AuthType }
     * 
     */
    public AuthType createAuthType() {
        return new AuthType();
    }

    /**
     * Create an instance of {@link TrapTypeIconType }
     * 
     */
    public TrapTypeIconType createTrapTypeIconType() {
        return new TrapTypeIconType();
    }

    /**
     * Create an instance of {@link ImageAttributeType }
     * 
     */
    public ImageAttributeType createImageAttributeType() {
        return new ImageAttributeType();
    }

    /**
     * Create an instance of {@link PoitopicsType }
     * 
     */
    public PoitopicsType createPoitopicsType() {
        return new PoitopicsType();
    }

    /**
     * Create an instance of {@link ThemeAttributeType }
     * 
     */
    public ThemeAttributeType createThemeAttributeType() {
        return new ThemeAttributeType();
    }

    /**
     * Create an instance of {@link ThemeLinkListType }
     * 
     */
    public ThemeLinkListType createThemeLinkListType() {
        return new ThemeLinkListType();
    }

    /**
     * Create an instance of {@link ThemeLinkFormatType }
     * 
     */
    public ThemeLinkFormatType createThemeLinkFormatType() {
        return new ThemeLinkFormatType();
    }

    /**
     * Create an instance of {@link MetaType }
     * 
     */
    public MetaType createMetaType() {
        return new MetaType();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link ImageSpecType }
     * 
     */
    public ImageSpecType createImageSpecType() {
        return new ImageSpecType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link TrapTypeLevelType }
     * 
     */
    public TrapTypeLevelType createTrapTypeLevelType() {
        return new TrapTypeLevelType();
    }

    /**
     * Create an instance of {@link TrapTypeAttributeType }
     * 
     */
    public TrapTypeAttributeType createTrapTypeAttributeType() {
        return new TrapTypeAttributeType();
    }

    /**
     * Create an instance of {@link StringAttributeType }
     * 
     */
    public StringAttributeType createStringAttributeType() {
        return new StringAttributeType();
    }

    /**
     * Create an instance of {@link PatrolPointType }
     * 
     */
    public PatrolPointType createPatrolPointType() {
        return new PatrolPointType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TrapsterType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.trapster.com/schema/2.0.0/trapster", name = "trapster")
    public JAXBElement<TrapsterType> createTrapster(TrapsterType value) {
        return new JAXBElement<TrapsterType>(_Trapster_QNAME, TrapsterType.class, null, value);
    }

}
