//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.trapster.com/schema/2.0.0/trapster", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.navteq.lbsp.ctg.trapster.modules.commons.domain;
