//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for paramsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="paramsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="radius" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="numvotes" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="highestusercred" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="traptypeids" type="{http://www.w3.org/2001/XMLSchema}long" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sortorder" type="{http://www.w3.org/2001/XMLSchema}NCName" minOccurs="0"/>
 *         &lt;element name="addr" type="{http://www.w3.org/2001/XMLSchema}NCName" minOccurs="0"/>
 *         &lt;element name="maxresults" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="vote" type="{http://www.w3.org/2001/XMLSchema}NCName" minOccurs="0"/>
 *         &lt;element name="trapid" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="login" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="displayname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailaddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwdusernamehash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwdemailhash" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="usercredlevel" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alertradius" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="signupepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastvoteepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="totaluservotes" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="karma" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="tosagreed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="trustedgrouppref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="privmsgpref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="smsaddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="moderatorlevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loggedontositeflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="newsletterflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailconfflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userstatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lastkarma" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sipallowedflag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="loginfailures" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="modapplyepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastapiepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="lastwebepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="confirmepochtime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="confirmmethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pwd" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="pwdcnf" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="carrier" type="{http://www.w3.org/2001/XMLSchema}NCName"/>
 *         &lt;element name="modifiedaftertime" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="points" type="{http://www.trapster.com/schema/2.0.0/trapster}point" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paramsType", propOrder = {
    "latitude",
    "longitude",
    "radius",
    "numvotes",
    "highestusercred",
    "traptypeids",
    "sortorder",
    "addr",
    "maxresults",
    "vote",
    "trapid",
    "id",
    "login",
    "displayname",
    "emailaddr",
    "pwdusernamehash",
    "pwdemailhash",
    "usercredlevel",
    "info",
    "alertradius",
    "alert",
    "signupepochtime",
    "lastvoteepochtime",
    "totaluservotes",
    "karma",
    "tosagreed",
    "trustedgrouppref",
    "privmsgpref",
    "smsaddr",
    "moderatorlevel",
    "loggedontositeflag",
    "newsletterflag",
    "emailconfflag",
    "userstatus",
    "lastkarma",
    "sipallowedflag",
    "loginfailures",
    "modapplyepochtime",
    "lastapiepochtime",
    "lastwebepochtime",
    "confirmepochtime",
    "confirmmethod",
    "pwd",
    "pwdcnf",
    "carrier",
    "modifiedaftertime",
    "points"
})
public class ParamsType {

    protected Double latitude;
    protected Double longitude;
    protected Double radius;
    protected Integer numvotes;
    protected Integer highestusercred;
    @XmlElement(type = Long.class)
    protected List<Long> traptypeids;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sortorder;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String addr;
    protected Integer maxresults;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String vote;
    protected Long trapid;
    protected Long id;
    protected String login;
    protected String displayname;
    protected String emailaddr;
    protected String pwdusernamehash;
    protected String pwdemailhash;
    protected Integer usercredlevel;
    protected String info;
    protected Double alertradius;
    protected String alert;
    protected Long signupepochtime;
    protected Long lastvoteepochtime;
    protected Integer totaluservotes;
    protected Integer karma;
    protected String tosagreed;
    protected String trustedgrouppref;
    protected String privmsgpref;
    protected String smsaddr;
    protected String moderatorlevel;
    protected String loggedontositeflag;
    protected String newsletterflag;
    protected String emailconfflag;
    protected String userstatus;
    protected Integer lastkarma;
    protected String sipallowedflag;
    protected Integer loginfailures;
    protected Long modapplyepochtime;
    protected Long lastapiepochtime;
    protected Long lastwebepochtime;
    protected Long confirmepochtime;
    protected String confirmmethod;
    @XmlElement(required = true, nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pwd;
    @XmlElement(required = true, nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String pwdcnf;
    @XmlElement(required = true, nillable = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String carrier;
    protected Long modifiedaftertime;
    protected List<Point> points;

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLatitude(Double value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLongitude(Double value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRadius(Double value) {
        this.radius = value;
    }

    /**
     * Gets the value of the numvotes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumvotes() {
        return numvotes;
    }

    /**
     * Sets the value of the numvotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumvotes(Integer value) {
        this.numvotes = value;
    }

    /**
     * Gets the value of the highestusercred property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHighestusercred() {
        return highestusercred;
    }

    /**
     * Sets the value of the highestusercred property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHighestusercred(Integer value) {
        this.highestusercred = value;
    }

    /**
     * Gets the value of the traptypeids property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the traptypeids property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTraptypeids().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Long }
     * 
     * 
     */
    public List<Long> getTraptypeids() {
        if (traptypeids == null) {
            traptypeids = new ArrayList<Long>();
        }
        return this.traptypeids;
    }

    /**
     * Gets the value of the sortorder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortorder() {
        return sortorder;
    }

    /**
     * Sets the value of the sortorder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortorder(String value) {
        this.sortorder = value;
    }

    /**
     * Gets the value of the addr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the maxresults property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxresults() {
        return maxresults;
    }

    /**
     * Sets the value of the maxresults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxresults(Integer value) {
        this.maxresults = value;
    }

    /**
     * Gets the value of the vote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVote() {
        return vote;
    }

    /**
     * Sets the value of the vote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVote(String value) {
        this.vote = value;
    }

    /**
     * Gets the value of the trapid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTrapid() {
        return trapid;
    }

    /**
     * Sets the value of the trapid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTrapid(Long value) {
        this.trapid = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the login property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogin() {
        return login;
    }

    /**
     * Sets the value of the login property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogin(String value) {
        this.login = value;
    }

    /**
     * Gets the value of the displayname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayname() {
        return displayname;
    }

    /**
     * Sets the value of the displayname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayname(String value) {
        this.displayname = value;
    }

    /**
     * Gets the value of the emailaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailaddr() {
        return emailaddr;
    }

    /**
     * Sets the value of the emailaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailaddr(String value) {
        this.emailaddr = value;
    }

    /**
     * Gets the value of the pwdusernamehash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwdusernamehash() {
        return pwdusernamehash;
    }

    /**
     * Sets the value of the pwdusernamehash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwdusernamehash(String value) {
        this.pwdusernamehash = value;
    }

    /**
     * Gets the value of the pwdemailhash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwdemailhash() {
        return pwdemailhash;
    }

    /**
     * Sets the value of the pwdemailhash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwdemailhash(String value) {
        this.pwdemailhash = value;
    }

    /**
     * Gets the value of the usercredlevel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getUsercredlevel() {
        return usercredlevel;
    }

    /**
     * Sets the value of the usercredlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setUsercredlevel(Integer value) {
        this.usercredlevel = value;
    }

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfo(String value) {
        this.info = value;
    }

    /**
     * Gets the value of the alertradius property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAlertradius() {
        return alertradius;
    }

    /**
     * Sets the value of the alertradius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAlertradius(Double value) {
        this.alertradius = value;
    }

    /**
     * Gets the value of the alert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlert() {
        return alert;
    }

    /**
     * Sets the value of the alert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlert(String value) {
        this.alert = value;
    }

    /**
     * Gets the value of the signupepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSignupepochtime() {
        return signupepochtime;
    }

    /**
     * Sets the value of the signupepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSignupepochtime(Long value) {
        this.signupepochtime = value;
    }

    /**
     * Gets the value of the lastvoteepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastvoteepochtime() {
        return lastvoteepochtime;
    }

    /**
     * Sets the value of the lastvoteepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastvoteepochtime(Long value) {
        this.lastvoteepochtime = value;
    }

    /**
     * Gets the value of the totaluservotes property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotaluservotes() {
        return totaluservotes;
    }

    /**
     * Sets the value of the totaluservotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotaluservotes(Integer value) {
        this.totaluservotes = value;
    }

    /**
     * Gets the value of the karma property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getKarma() {
        return karma;
    }

    /**
     * Sets the value of the karma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setKarma(Integer value) {
        this.karma = value;
    }

    /**
     * Gets the value of the tosagreed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTosagreed() {
        return tosagreed;
    }

    /**
     * Sets the value of the tosagreed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTosagreed(String value) {
        this.tosagreed = value;
    }

    /**
     * Gets the value of the trustedgrouppref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrustedgrouppref() {
        return trustedgrouppref;
    }

    /**
     * Sets the value of the trustedgrouppref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrustedgrouppref(String value) {
        this.trustedgrouppref = value;
    }

    /**
     * Gets the value of the privmsgpref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivmsgpref() {
        return privmsgpref;
    }

    /**
     * Sets the value of the privmsgpref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivmsgpref(String value) {
        this.privmsgpref = value;
    }

    /**
     * Gets the value of the smsaddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmsaddr() {
        return smsaddr;
    }

    /**
     * Sets the value of the smsaddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmsaddr(String value) {
        this.smsaddr = value;
    }

    /**
     * Gets the value of the moderatorlevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModeratorlevel() {
        return moderatorlevel;
    }

    /**
     * Sets the value of the moderatorlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModeratorlevel(String value) {
        this.moderatorlevel = value;
    }

    /**
     * Gets the value of the loggedontositeflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggedontositeflag() {
        return loggedontositeflag;
    }

    /**
     * Sets the value of the loggedontositeflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggedontositeflag(String value) {
        this.loggedontositeflag = value;
    }

    /**
     * Gets the value of the newsletterflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsletterflag() {
        return newsletterflag;
    }

    /**
     * Sets the value of the newsletterflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsletterflag(String value) {
        this.newsletterflag = value;
    }

    /**
     * Gets the value of the emailconfflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailconfflag() {
        return emailconfflag;
    }

    /**
     * Sets the value of the emailconfflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailconfflag(String value) {
        this.emailconfflag = value;
    }

    /**
     * Gets the value of the userstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserstatus() {
        return userstatus;
    }

    /**
     * Sets the value of the userstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserstatus(String value) {
        this.userstatus = value;
    }

    /**
     * Gets the value of the lastkarma property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastkarma() {
        return lastkarma;
    }

    /**
     * Sets the value of the lastkarma property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastkarma(Integer value) {
        this.lastkarma = value;
    }

    /**
     * Gets the value of the sipallowedflag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSipallowedflag() {
        return sipallowedflag;
    }

    /**
     * Sets the value of the sipallowedflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSipallowedflag(String value) {
        this.sipallowedflag = value;
    }

    /**
     * Gets the value of the loginfailures property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLoginfailures() {
        return loginfailures;
    }

    /**
     * Sets the value of the loginfailures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLoginfailures(Integer value) {
        this.loginfailures = value;
    }

    /**
     * Gets the value of the modapplyepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getModapplyepochtime() {
        return modapplyepochtime;
    }

    /**
     * Sets the value of the modapplyepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setModapplyepochtime(Long value) {
        this.modapplyepochtime = value;
    }

    /**
     * Gets the value of the lastapiepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastapiepochtime() {
        return lastapiepochtime;
    }

    /**
     * Sets the value of the lastapiepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastapiepochtime(Long value) {
        this.lastapiepochtime = value;
    }

    /**
     * Gets the value of the lastwebepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLastwebepochtime() {
        return lastwebepochtime;
    }

    /**
     * Sets the value of the lastwebepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLastwebepochtime(Long value) {
        this.lastwebepochtime = value;
    }

    /**
     * Gets the value of the confirmepochtime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getConfirmepochtime() {
        return confirmepochtime;
    }

    /**
     * Sets the value of the confirmepochtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setConfirmepochtime(Long value) {
        this.confirmepochtime = value;
    }

    /**
     * Gets the value of the confirmmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfirmmethod() {
        return confirmmethod;
    }

    /**
     * Sets the value of the confirmmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfirmmethod(String value) {
        this.confirmmethod = value;
    }

    /**
     * Gets the value of the pwd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * Sets the value of the pwd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwd(String value) {
        this.pwd = value;
    }

    /**
     * Gets the value of the pwdcnf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPwdcnf() {
        return pwdcnf;
    }

    /**
     * Sets the value of the pwdcnf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPwdcnf(String value) {
        this.pwdcnf = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrier(String value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the modifiedaftertime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getModifiedaftertime() {
        return modifiedaftertime;
    }

    /**
     * Sets the value of the modifiedaftertime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setModifiedaftertime(Long value) {
        this.modifiedaftertime = value;
    }

    /**
     * Gets the value of the points property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the points property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Point }
     * 
     * 
     */
    public List<Point> getPoints() {
        if (points == null) {
            points = new ArrayList<Point>();
        }
        return this.points;
    }

}
