//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for themeLinkFormatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="themeLinkFormatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aiff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mp3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "themeLinkFormatType", propOrder = {
    "aiff",
    "mp3"
})
public class ThemeLinkFormatType {

    protected String aiff;
    protected String mp3;

    /**
     * Gets the value of the aiff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAiff() {
        return aiff;
    }

    /**
     * Sets the value of the aiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAiff(String value) {
        this.aiff = value;
    }

    /**
     * Gets the value of the mp3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMp3() {
        return mp3;
    }

    /**
     * Sets the value of the mp3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMp3(String value) {
        this.mp3 = value;
    }

}
