//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.30 at 01:06:27 PM EDT 
//


package com.navteq.lbsp.ctg.trapster.modules.commons.domain;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trapTypeIconType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trapTypeIconType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alt2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="alt1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="base" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trapTypeIconType", propOrder = {
    "alt2",
    "alt1",
    "base"
})
public class TrapTypeIconType {

    @XmlElement(required = true)
    protected String alt2;
    @XmlElement(required = true)
    protected String alt1;
    @XmlElement(required = true)
    protected String base;

    /**
     * Gets the value of the alt2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt2() {
        return alt2;
    }

    /**
     * Sets the value of the alt2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt2(String value) {
        this.alt2 = value;
    }

    /**
     * Gets the value of the alt1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlt1() {
        return alt1;
    }

    /**
     * Sets the value of the alt1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlt1(String value) {
        this.alt1 = value;
    }

    /**
     * Gets the value of the base property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBase() {
        return base;
    }

    /**
     * Sets the value of the base property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBase(String value) {
        this.base = value;
    }

}
